version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data

  airflow:
    image: apache/airflow:2.9.0
    container_name: airflow
    depends_on:
      - minio
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - _AIRFLOW_WWW_USER_FIRSTNAME=Admin
      - _AIRFLOW_WWW_USER_LASTNAME=User
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - _AIRFLOW_WWW_USER_EMAIL=admin@openmacrolake.io
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./airflow_home:/opt/airflow
      - ./.env:/opt/airflow/.env
    command: bash -c "
      airflow db migrate &&
      airflow users create \
        --username airflow \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@openmacrolake.io \
        --password airflow || true &&
      airflow standalone
      "

  spark:
    image: public.ecr.aws/bitnami/spark:latest
    container_name: spark
    user: root
    depends_on:
      - minio
    ports:
      - "4040:4040"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark:7077
      - PYSPARK_PYTHON=python3
      - HADOOP_USER_NAME=root
      - USER=root
      - HOME=/root
      - JAVA_TOOL_OPTIONS=-Duser.name=root
      - SPARK_SUBMIT_OPTS=-Duser.name=root
      - SPARK_LOCAL_DIRS=/tmp/spark
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf
      - HADOOP_OPTS=-Djava.security.krb5.realm= -Djava.security.krb5.kdc=
      - SPARK_SQL_WAREHOUSE_DIR=/tmp/spark-warehouse
      - SPARK_JARS_IVY=/root/.ivy2
      - SPARK_DRIVER_HOST=spark
      - SPARK_DIST_CLASSPATH=/opt/bitnami/spark/jars/*
      - PYTHONPATH=/src

    volumes:
      - ./src:/src
      - ./data:/data
      - ./tmp:/tmp/spark
      - ./ivy2:/root/.ivy2   